image: node:8.11.1

before_script:
  - npm install

stages:
  - test

test:
  stage: test
  only:
    - /^(release\/|master).*$/
    - tags
    - schedules
    - web
    - triggers
  script:
   - npm test
  artifacts:
    expire_in: 30 days
    paths:
      - .coverage-report/
